default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  port: 5432
  database: compass_development

test:
  <<: *default
  database: compass_test

production:
  <<: *default
  database: compass_production
  username: compass
  password: <%= ENV['COMPASS_DATABASE_PASSWORD'] %>
  port: 5432
